PackageIdentifier: PixPin.PixPin
PackageVersion: 1.8.22.0
PackageName: PixPin
Publisher: PixPin
License: Proprietary
ShortDescription: Lightweight screenshot and annotation tool.
Installers:
  - Architecture: x64
    InstallerType: exe
    InstallerUrl: https://download.pixpinapp.com/PixPin_1.8.22.0.exe
    InstallerSha256: E1B3F45B6D3C54266684D0E787AF18CC0816A115DBCD63AD4162F256FD6AB979
    SilentInstallSwitch: /S
    InstallLocationRequired: false
ManifestType: singleton
ManifestVersion: 1.6.0
